Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

================ RESTART: C:/Users/16129532024.5/Documents/10.py ===============
Digite um número:2
Digite outro número:3
O resultado da soma é: 5
O resultado da subtração: -1
Traceback (most recent call last):
  File "C:/Users/16129532024.5/Documents/10.py", line 10, in <module>
    print("O resultado da multiplicacao é", MULTIPLICACAO)
NameError: name 'MULTIPLICACAO' is not defined

================ RESTART: C:/Users/16129532024.5/Documents/10.py ===============
O resultado da expressão #1 é: 25.0
Traceback (most recent call last):
  File "C:/Users/16129532024.5/Documents/10.py", line 6, in <module>
    VALOR = ((y . x) + (z .x)) / 3
AttributeError: 'int' object has no attribute 'x'

================ RESTART: C:/Users/16129532024.5/Documents/10.py ===============
O resultado da expressão #1 é: 25.0
Traceback (most recent call last):
  File "C:/Users/16129532024.5/Documents/10.py", line 6, in <module>
    VALOR = ((y . x) + (z . x)) / 3
AttributeError: 'int' object has no attribute 'x'
